[package]
name = "ml_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
matrix = { path = "./lib/matrix"}
layer ={ path = "./lib/layer" }


[[bench]]
name="matrix"
harness=false
